name: Run K-Drama Ranking Bot

on:
  schedule:
    # 🚨 전 세계 봇 출근 시간을 피해서 오전 8시 17분으로 꼼수 세팅! (UTC 23:17)
    - cron: '17 23 * * *'
  
  # 수동 실행 기능
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Node.js 24버전 경고 해결용
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # [경고 해결] v3 -> v4 로 업데이트

      - name: Set up Python
        uses: actions/setup-python@v5  # [경고 해결] v4 -> v5 로 업데이트
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
